In [8]:
import pandas as pd
import numpy as np

In [9]:
data = {'creatures': ['Eagles', 'Eagles', 'Ducks', 'Herons', 'Herons', 
'Eagles', 'Ducks', 'Eagles', 'Herons', 'Herons', 'Eagles'],  
'weight': [2.0, 5, 3.0, np.nan, 7, 2.5, 6, np.nan, 9, 3, 2.0],  
'frequency': [1, 3, 2, 5, 2, 3, 1, 3, 4, 2, 1],  
'status': ['no', 'no', 'yes', np.nan, 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 
'no'],  
'height': [1.2, 2.5, 1.8, 3.0, 2.2, 1.9, 2.6, 1.4, 2.8, 2.3, 1.1],  
'region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 
'West', 'North', 'East', 'South'],  
'danger_level': ['low', 'medium', 'high', 'low', 'high', 'medium', 
'high', 'low', 'medium', 'high', 'low']} 
labels = ['x', 'y', 'z', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p']

In [10]:
#create a dataframe
df = pd.DataFrame(data, index=labels)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, x to p
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   creatures     11 non-null     object
 1   weight        9 non-null      float64
 2   frequency     11 non-null     int64
 3   status        10 non-null     object
 4   height        11 non-null     float64
 5   region        11 non-null     object
 6   danger_level  11 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 704.0+ bytes

In [11]:
#Write a program to display the basic information of the DataFrame, including its summary statistics and data types.
df.info()
df.describe()
df.dtypes

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, x to p
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   creatures     11 non-null     object
 1   weight        9 non-null      float64
 2   frequency     11 non-null     int64
 3   status        10 non-null     object
 4   height        11 non-null     float64
 5   region        11 non-null     object
 6   danger_level  11 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 704.0+ bytes

creatures        object
weight          float64
frequency         int64
status           object
height          float64
region           object
danger_level     object
dtype: object

In [12]:
#Write a program to display every alternate row of the DataFrame (starting from index 0). 
df.iloc[::2]

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
z     Ducks     3.0          2    yes     1.8   East         high
v    Herons     7.0          2    yes     2.2  North         high
t     Ducks     6.0          1    yes     2.6   East         high
r    Herons     9.0          4    yes     2.8  North       medium
p    Eagles     2.0          1     no     1.1  South          low

In [13]:
#Write a program to display only rows at index positions 1st, 3rd, and 7th from columns creatures and weight of the DataFrame. 
df.loc[['y', 'w', 's'], ['creatures', 'weight']]

  creatures  weight
y    Eagles     5.0
w    Herons     NaN
s    Eagles     NaN

In [14]:
#Write a program to select and display the rows where the frequency is less than 4. 
df[df['frequency']<4]

  creatures  weight  frequency status  height region danger_level
x    Eagles     2.0          1     no     1.2  North          low
y    Eagles     5.0          3     no     2.5  South       medium
z     Ducks     3.0          2    yes     1.8   East         high
v    Herons     7.0          2    yes     2.2  North         high
u    Eagles     2.5          3    yes     1.9  South       medium
t     Ducks     6.0          1    yes     2.6   East         high
s    Eagles     NaN          3     no     1.4   West          low
q    Herons     3.0          2    yes     2.3   East         high
p    Eagles     2.0          1     no     1.1  South          low