In [7]:

#! pip install pandas
! pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from seaborn) (2.4.4)
Requirement already satisfied: pandas>=1.2 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from seaborn) (3.0.2)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Downloading matplotlib-3.10.8-cp314-cp314-win_amd64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading fonttools-4.62.1-cp314-cp314-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Collecting pillow>=8 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pillow-12.2.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from pandas>=1.2->seaborn) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading matplotlib-3.10.8-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.3 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.3 MB 337.5 kB/s eta 0:00:23
   -- ------------------------------------- 0.5/8.3 MB 337.5 kB/s eta 0:00:23
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/8.3 MB 378.0 kB/s eta 0:00:20
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ----- ---------------------------------- 1.0/8.3 MB 136.8 kB/s eta 0:00:53
   ------ --------------------------------- 1.3/8.3 MB 87.9 kB/s eta 0:01:20
   ------ --------------------------------- 1.3/8.3 MB 87.9 kB/s eta 0:01:20
   ------ --------------------------------- 1.3/8.3 MB 87.9 kB/s eta 0:01:20
   ------ --------------------------------- 1.3/8.3 MB 87.9 kB/s eta 0:01:20
   ------ --------------------------------- 1.3/8.3 MB 87.9 kB/s eta 0:01:20
   ------ --------------------------------- 1.3/8.3 MB 87.9 kB/s eta 0:01:20
   ------ --------------------------------- 1.3/8.3 MB 87.9 kB/s eta 0:01:20
   ------ --------------------------------- 1.3/8.3 MB 87.9 kB/s eta 0:01:20
   ------ --------------------------------- 1.3/8.3 MB 87.9 kB/s eta 0:01:20
   ------ --------------------------------- 1.3/8.3 MB 87.9 kB/s eta 0:01:20
   ------- -------------------------------- 1.6/8.3 MB 94.0 kB/s eta 0:01:12
   ------- -------------------------------- 1.6/8.3 MB 94.0 kB/s eta 0:01:12
   ------- -------------------------------- 1.6/8.3 MB 94.0 kB/s eta 0:01:12
   ------- -------------------------------- 1.6/8.3 MB 94.0 kB/s eta 0:01:12
   ------- -------------------------------- 1.6/8.3 MB 94.0 kB/s eta 0:01:12
   ------- -------------------------------- 1.6/8.3 MB 94.0 kB/s eta 0:01:12
   -------- ------------------------------- 1.8/8.3 MB 102.7 kB/s eta 0:01:03
   -------- ------------------------------- 1.8/8.3 MB 102.7 kB/s eta 0:01:03
   -------- ------------------------------- 1.8/8.3 MB 102.7 kB/s eta 0:01:03
   -------- ------------------------------- 1.8/8.3 MB 102.7 kB/s eta 0:01:03
   -------- ------------------------------- 1.8/8.3 MB 102.7 kB/s eta 0:01:03
   ---------- ----------------------------- 2.1/8.3 MB 112.9 kB/s eta 0:00:55
   ---------- ----------------------------- 2.1/8.3 MB 112.9 kB/s eta 0:00:55
   ---------- ----------------------------- 2.1/8.3 MB 112.9 kB/s eta 0:00:55
   ---------- ----------------------------- 2.1/8.3 MB 112.9 kB/s eta 0:00:55
   ---------- ----------------------------- 2.1/8.3 MB 112.9 kB/s eta 0:00:55
   ---------- ----------------------------- 2.1/8.3 MB 112.9 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.3 MB 119.9 kB/s eta 0:00:50
   ----------- ---------------------------- 2.4/8.3 MB 119.9 kB/s eta 0:00:50
   ----------- ---------------------------- 2.4/8.3 MB 119.9 kB/s eta 0:00:50
   ----------- ---------------------------- 2.4/8.3 MB 119.9 kB/s eta 0:00:50
   ----------- ---------------------------- 2.4/8.3 MB 119.9 kB/s eta 0:00:50
   ----------- ---------------------------- 2.4/8.3 MB 119.9 kB/s eta 0:00:50
   ----------- ---------------------------- 2.4/8.3 MB 119.9 kB/s eta 0:00:50
   ----------- ---------------------------- 2.4/8.3 MB 119.9 kB/s eta 0:00:50
   ------------ --------------------------- 2.6/8.3 MB 122.6 kB/s eta 0:00:47
   ------------ --------------------------- 2.6/8.3 MB 122.6 kB/s eta 0:00:47
   ------------ --------------------------- 2.6/8.3 MB 122.6 kB/s eta 0:00:47
   ------------ --------------------------- 2.6/8.3 MB 122.6 kB/s eta 0:00:47
   ------------ --------------------------- 2.6/8.3 MB 122.6 kB/s eta 0:00:47
   ------------ --------------------------- 2.6/8.3 MB 122.6 kB/s eta 0:00:47
   ------------- -------------------------- 2.9/8.3 MB 127.4 kB/s eta 0:00:43
   ------------- -------------------------- 2.9/8.3 MB 127.4 kB/s eta 0:00:43
   ------------- -------------------------- 2.9/8.3 MB 127.4 kB/s eta 0:00:43
   ------------- -------------------------- 2.9/8.3 MB 127.4 kB/s eta 0:00:43
   ------------- -------------------------- 2.9/8.3 MB 127.4 kB/s eta 0:00:43
   ------------- -------------------------- 2.9/8.3 MB 127.4 kB/s eta 0:00:43
   ------------- -------------------------- 2.9/8.3 MB 127.4 kB/s eta 0:00:43
   ------------- -------------------------- 2.9/8.3 MB 127.4 kB/s eta 0:00:43
   ------------- -------------------------- 2.9/8.3 MB 127.4 kB/s eta 0:00:43
   --------------- ------------------------ 3.1/8.3 MB 128.7 kB/s eta 0:00:40
   --------------- ------------------------ 3.1/8.3 MB 128.7 kB/s eta 0:00:40
   --------------- ------------------------ 3.1/8.3 MB 128.7 kB/s eta 0:00:40
   --------------- ------------------------ 3.1/8.3 MB 128.7 kB/s eta 0:00:40
   --------------- ------------------------ 3.1/8.3 MB 128.7 kB/s eta 0:00:40
   --------------- ------------------------ 3.1/8.3 MB 128.7 kB/s eta 0:00:40
   ---------------- ----------------------- 3.4/8.3 MB 132.8 kB/s eta 0:00:37
   ---------------- ----------------------- 3.4/8.3 MB 132.8 kB/s eta 0:00:37
   ---------------- ----------------------- 3.4/8.3 MB 132.8 kB/s eta 0:00:37
   ---------------- ----------------------- 3.4/8.3 MB 132.8 kB/s eta 0:00:37
   ---------------- ----------------------- 3.4/8.3 MB 132.8 kB/s eta 0:00:37
   ---------------- ----------------------- 3.4/8.3 MB 132.8 kB/s eta 0:00:37
   ---------------- ----------------------- 3.4/8.3 MB 132.8 kB/s eta 0:00:37
   ---------------- ----------------------- 3.4/8.3 MB 132.8 kB/s eta 0:00:37
   ---------------- ----------------------- 3.4/8.3 MB 132.8 kB/s eta 0:00:37
   ---------------- ----------------------- 3.4/8.3 MB 132.8 kB/s eta 0:00:37
   ----------------- ---------------------- 3.7/8.3 MB 132.6 kB/s eta 0:00:35
   ----------------- ---------------------- 3.7/8.3 MB 132.6 kB/s eta 0:00:35
   ----------------- ---------------------- 3.7/8.3 MB 132.6 kB/s eta 0:00:35
   ----------------- ---------------------- 3.7/8.3 MB 132.6 kB/s eta 0:00:35
   ----------------- ---------------------- 3.7/8.3 MB 132.6 kB/s eta 0:00:35
   ----------------- ---------------------- 3.7/8.3 MB 132.6 kB/s eta 0:00:35
   ----------------- ---------------------- 3.7/8.3 MB 132.6 kB/s eta 0:00:35
   ----------------- ---------------------- 3.7/8.3 MB 132.6 kB/s eta 0:00:35
   ----------------- ---------------------- 3.7/8.3 MB 132.6 kB/s eta 0:00:35
   ----------------- ---------------------- 3.7/8.3 MB 132.6 kB/s eta 0:00:35
   ----------------- ---------------------- 3.7/8.3 MB 132.6 kB/s eta 0:00:35
   ----------------- ---------------------- 3.7/8.3 MB 132.6 kB/s eta 0:00:35
   ----------------- ---------------------- 3.7/8.3 MB 132.6 kB/s eta 0:00:35
   ----------------- ---------------------- 3.7/8.3 MB 132.6 kB/s eta 0:00:35
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   ------------------- -------------------- 3.9/8.3 MB 127.8 kB/s eta 0:00:34
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   -------------------- ------------------- 4.2/8.3 MB 114.4 kB/s eta 0:00:36
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   --------------------- ------------------ 4.5/8.3 MB 128.5 kB/s eta 0:00:30
   ---------------------- ----------------- 4.7/8.3 MB 123.9 kB/s eta 0:00:29
   ---------------------- ----------------- 4.7/8.3 MB 123.9 kB/s eta 0:00:29
   ---------------------- ----------------- 4.7/8.3 MB 123.9 kB/s eta 0:00:29
   ---------------------- ----------------- 4.7/8.3 MB 123.9 kB/s eta 0:00:29
   ---------------------- ----------------- 4.7/8.3 MB 123.9 kB/s eta 0:00:29
   ---------------------- ----------------- 4.7/8.3 MB 123.9 kB/s eta 0:00:29
   ------------------------ --------------- 5.0/8.3 MB 127.8 kB/s eta 0:00:26
   ------------------------ --------------- 5.0/8.3 MB 127.8 kB/s eta 0:00:26
   ------------------------ --------------- 5.0/8.3 MB 127.8 kB/s eta 0:00:26
   ------------------------- -------------- 5.2/8.3 MB 133.2 kB/s eta 0:00:23
   ------------------------- -------------- 5.2/8.3 MB 133.2 kB/s eta 0:00:23
   ------------------------- -------------- 5.2/8.3 MB 133.2 kB/s eta 0:00:23
   ------------------------- -------------- 5.2/8.3 MB 133.2 kB/s eta 0:00:23
   -------------------------- ------------- 5.5/8.3 MB 139.3 kB/s eta 0:00:20
   -------------------------- ------------- 5.5/8.3 MB 139.3 kB/s eta 0:00:20
   -------------------------- ------------- 5.5/8.3 MB 139.3 kB/s eta 0:00:20
   --------------------------- ------------ 5.8/8.3 MB 145.4 kB/s eta 0:00:18
   --------------------------- ------------ 5.8/8.3 MB 145.4 kB/s eta 0:00:18
   ----------------------------- ---------- 6.0/8.3 MB 151.7 kB/s eta 0:00:15
   ----------------------------- ---------- 6.0/8.3 MB 151.7 kB/s eta 0:00:15
   ------------------------------ --------- 6.3/8.3 MB 158.3 kB/s eta 0:00:13
   ------------------------------ --------- 6.3/8.3 MB 158.3 kB/s eta 0:00:13
   ------------------------------- -------- 6.6/8.3 MB 164.5 kB/s eta 0:00:11
   -------------------------------- ------- 6.8/8.3 MB 172.1 kB/s eta 0:00:09
   ---------------------------------- ----- 7.1/8.3 MB 179.8 kB/s eta 0:00:07
   ----------------------------------- ---- 7.3/8.3 MB 187.2 kB/s eta 0:00:05
   ------------------------------------ --- 7.6/8.3 MB 195.1 kB/s eta 0:00:04
   -------------------------------------- - 7.9/8.3 MB 202.4 kB/s eta 0:00:03
   ---------------------------------------  8.1/8.3 MB 210.0 kB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 211.5 kB/s  0:00:46
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--

WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (0 bytes/7.2 MB, attempt 1)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002986DBA8190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/cd/8b/601e6566b957ca50e28725cb6c355c59c2c8609751efbecd980db44e0349/pillow-12.2.0-cp314-cp314-win_amd64.whl

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from seaborn) (2.4.4)
Requirement already satisfied: pandas>=1.2 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from seaborn) (3.0.2)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Using cached matplotlib-3.10.8-cp314-cp314-win_amd64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached fonttools-4.62.1-cp314-cp314-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Collecting pillow>=8 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached pillow-12.2.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from pandas>=1.2->seaborn) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached matplotlib-3.10.8-cp314-cp314-win_amd64.whl (8.3 MB)
Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.62.1-cp314-cp314-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Downloading pillow-12.2.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   -- ------------------------------------- 0.5/7.2 MB 59.7 kB/s eta 0:01:53
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ---- ----------------------------------- 0.8/7.2 MB 60.2 kB/s eta 0:01:47
   ----- ---------------------------------- 1.0/7.2 MB 54.8 kB/s eta 0:01:53
   ----- ---------------------------------- 1.0/7.2 MB 54.8 kB/s eta 0:01:53
   ----- ---------------------------------- 1.0/7.2 MB 54.8 kB/s eta 0:01:53
   ----- ---------------------------------- 1.0/7.2 MB 54.8 kB/s eta 0:01:53
   ----- ---------------------------------- 1.0/7.2 MB 54.8 kB/s eta 0:01:53
   ----- ---------------------------------- 1.0/7.2 MB 54.8 kB/s eta 0:01:53
   ----- ---------------------------------- 1.0/7.2 MB 54.8 kB/s eta 0:01:53
   ----- ---------------------------------- 1.0/7.2 MB 54.8 kB/s eta 0:01:53
   ----- ---------------------------------- 1.0/7.2 MB 54.8 kB/s eta 0:01:53
   ----- ---------------------------------- 1.0/7.2 MB 54.8 kB/s eta 0:01:53
   ----- ---------------------------------- 1.0/7.2 MB 54.8 kB/s eta 0:01:53
   ----- ---------------------------------- 1.0/7.2 MB 54.8 kB/s eta 0:01:53
   ------- -------------------------------- 1.3/7.2 MB 62.2 kB/s eta 0:01:35
   ------- -------------------------------- 1.3/7.2 MB 62.2 kB/s eta 0:01:35
   ------- -------------------------------- 1.3/7.2 MB 62.2 kB/s eta 0:01:35
   -------- ------------------------------- 1.6/7.2 MB 75.0 kB/s eta 0:01:16
   -------- ------------------------------- 1.6/7.2 MB 75.0 kB/s eta 0:01:16
   -------- ------------------------------- 1.6/7.2 MB 75.0 kB/s eta 0:01:16
   ---------- ----------------------------- 1.8/7.2 MB 87.1 kB/s eta 0:01:02
   ---------- ----------------------------- 1.8/7.2 MB 87.1 kB/s eta 0:01:02
   ----------- ---------------------------- 2.1/7.2 MB 99.0 kB/s eta 0:00:52
   ----------- ---------------------------- 2.1/7.2 MB 99.0 kB/s eta 0:00:52
   ----------- ---------------------------- 2.1/7.2 MB 99.0 kB/s eta 0:00:52
   ----------- ---------------------------- 2.1/7.2 MB 99.0 kB/s eta 0:00:52
   ----------- ---------------------------- 2.1/7.2 MB 99.0 kB/s eta 0:00:52
   ----------- ---------------------------- 2.1/7.2 MB 99.0 kB/s eta 0:00:52
   ----------- ---------------------------- 2.1/7.2 MB 99.0 kB/s eta 0:00:52
   ----------- ---------------------------- 2.1/7.2 MB 99.0 kB/s eta 0:00:52
   ----------- ---------------------------- 2.1/7.2 MB 99.0 kB/s eta 0:00:52
   ----------- ---------------------------- 2.1/7.2 MB 99.0 kB/s eta 0:00:52
   ----------- ---------------------------- 2.1/7.2 MB 99.0 kB/s eta 0:00:52
   ----------- ---------------------------- 2.1/7.2 MB 99.0 kB/s eta 0:00:52
   ------------- -------------------------- 2.4/7.2 MB 99.8 kB/s eta 0:00:49
   ------------- -------------------------- 2.4/7.2 MB 99.8 kB/s eta 0:00:49
   ------------- -------------------------- 2.4/7.2 MB 99.8 kB/s eta 0:00:49
   ------------- -------------------------- 2.4/7.2 MB 99.8 kB/s eta 0:00:49
   ------------- -------------------------- 2.4/7.2 MB 99.8 kB/s eta 0:00:49
   -------------- ------------------------- 2.6/7.2 MB 107.0 kB/s eta 0:00:43
   -------------- ------------------------- 2.6/7.2 MB 107.0 kB/s eta 0:00:43
   --------------- ------------------------ 2.9/7.2 MB 116.1 kB/s eta 0:00:38
   --------------- ------------------------ 2.9/7.2 MB 116.1 kB/s eta 0:00:38
   --------------- ------------------------ 2.9/7.2 MB 116.1 kB/s eta 0:00:38
   ----------------- ---------------------- 3.1/7.2 MB 124.9 kB/s eta 0:00:33
   ----------------- ---------------------- 3.1/7.2 MB 124.9 kB/s eta 0:00:33
   ----------------- ---------------------- 3.1/7.2 MB 124.9 kB/s eta 0:00:33
   ------------------ --------------------- 3.4/7.2 MB 131.8 kB/s eta 0:00:29
   ------------------ --------------------- 3.4/7.2 MB 131.8 kB/s eta 0:00:29
   ------------------ --------------------- 3.4/7.2 MB 131.8 kB/s eta 0:00:29
   -------------------- ------------------- 3.7/7.2 MB 139.4 kB/s eta 0:00:26
   -------------------- ------------------- 3.7/7.2 MB 139.4 kB/s eta 0:00:26
   -------------------- ------------------- 3.7/7.2 MB 139.4 kB/s eta 0:00:26
   --------------------- ------------------ 3.9/7.2 MB 147.0 kB/s eta 0:00:23
   --------------------- ------------------ 3.9/7.2 MB 147.0 kB/s eta 0:00:23
   --------------------- ------------------ 3.9/7.2 MB 147.0 kB/s eta 0:00:23
   ----------------------- ---------------- 4.2/7.2 MB 153.5 kB/s eta 0:00:20
   ----------------------- ---------------- 4.2/7.2 MB 153.5 kB/s eta 0:00:20
   ----------------------- ---------------- 4.2/7.2 MB 153.5 kB/s eta 0:00:20
   ----------------------- ---------------- 4.2/7.2 MB 153.5 kB/s eta 0:00:20
   ----------------------- ---------------- 4.2/7.2 MB 153.5 kB/s eta 0:00:20
   ----------------------- ---------------- 4.2/7.2 MB 153.5 kB/s eta 0:00:20
   ----------------------- ---------------- 4.2/7.2 MB 153.5 kB/s eta 0:00:20
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   ------------------------ --------------- 4.5/7.2 MB 154.8 kB/s eta 0:00:18
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   -------------------------- ------------- 4.7/7.2 MB 154.6 kB/s eta 0:00:17
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   --------------------------- ------------ 5.0/7.2 MB 157.0 kB/s eta 0:00:15
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14
   ----------------------------- ---------- 5.2/7.2 MB 151.7 kB/s eta 0:00:14

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/matplotlib/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000026D55760F50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/cd/8b/601e6566b957ca50e28725cb6c355c59c2c8609751efbecd980db44e0349/pillow-12.2.0-cp314-cp314-win_amd64.whl

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import pandas as pd
import seaborn as sns

In [5]:
#using lists
data_sample = [
    [50,60,47],
    [70,73,75],
    [10,400,34],
    [60,5,20]
]
data1 = pd.DataFrame(data_sample, columns=['Python', 'C++', 'Java'])

data1

   Python  C++  Java
0      50   60    47
1      70   73    75
2      10  400    34
3      60    5    20

In [ ]:
#using dicts
data_dict={
    'col1':[100,90,120,80,0,0],
    'col2':[80,70,100,50,0,0],
    'col3':[80,70,100,50,0,0],
    'col4':[80,70,100,50,0,0],

}
students= pd.DataFrame(data_dict)
#students.set_index('col1',inplace=True)
students

In [15]:
! pip3 install seaborn

Requirement already satisfied: seaborn in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from seaborn) (2.4.4)
Requirement already satisfied: pandas>=1.2 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from seaborn) (3.0.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from pandas>=1.2->seaborn) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\shashwat sen\desktop\ml\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import seaborn as sns

In [5]:
df1 = sns.load_dataset('iris')
titanic = sns.load_dataset('titanic')
df3 = sns.load_dataset('tips')
d4 = sns.load_dataset('flights')
d5 = sns.load_dataset('diamonds')
d6 = sns.load_dataset('penguins')
d7 = sns.load_dataset('exercise')
d8 = sns.load_dataset('planets')
d9 = sns.load_dataset('mpg')
d10 = sns.load_dataset('car_crashes')
d11 = sns.load_dataset('dots')
d12 = sns.load_dataset('anscombe')
d13 = sns.load_dataset('attention')
d14 = sns.load_dataset('brain_networks')
d15 = sns.load_dataset('geyser')
d16 = sns.load_dataset('dots')
d17 = sns.load_dataset('anscombe')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
print(titanic.head())
print(titanic.shape)

In [ ]:
#sammple given a dataframe, it will return a random row from the dataframe. It is useful when we want to check the data in the dataframe.
df2.sample(1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
120,0,2,male,21.0,2,0,73.5,S,Second,man,True,NaN,Southampton,no,False

In [33]:
df2.head(1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.25,S,Third,man,True,NaN,Southampton,no,False

In [34]:
df2.tail(1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
print(titanic.shape)

In [ ]:
#datatype
df3 = sns.load_dataset('tips')
print(titanic['Age'].dtypes)
print()
print(titanic.dtypes)

In [53]:
#index
#print(titanic.index)
#columns
print(titanic.columns)

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [ ]:
#Functions

In [54]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [55]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [ ]:
titanic.describe() #to get the statistical summary of the dataset

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [59]:
df3.isnull().sum() #to get the count of null values in each column of the dataset
df3.isnull() #to get the boolean values of null values in each column of the dataset

     total_bill    tip    sex  smoker    day   time   size
0         False  False  False   False  False  False  False
1         False  False  False   False  False  False  False
2         False  False  False   False  False  False  False
3         False  False  False   False  False  False  False
4         False  False  False   False  False  False  False
..          ...    ...    ...     ...    ...    ...    ...
239       False  False  False   False  False  False  False
240       False  False  False   False  False  False  False
241       False  False  False   False  False  False  False
242       False  False  False   False  False  False  False
243       False  False  False   False  False  False  False

[244 rows x 7 columns]

In [ ]:
#duplicate values
titanic.duplicated().sum() #to get the count of duplicate values in the dataset

np.int64(107)

In [ ]:
#drop duplicates
titanic.drop_duplicates(inplace=True) #to drop the duplicate values from the dataset

In [ ]:
Create list,dict,pd.read-now("titanic.csv"),sns.loaddataset("")
Read methods:           attributes:
1. head()               1. shape
2. tail()               2. columns
3. sample()             3. dtypes
4. describe()           4. index
5. info()               5. memory_usage
6. isnull()             6. isna
7. duplicated()         7. drop_duplicates 
7. duplicated()

In [64]:
df3.head(1)

    Bill   tip     sex smoker  day    time  Number
0  16.99  1.01  Female     No  Sun  Dinner       2

In [63]:
df3.rename(columns={'total_bill':'Bill'}, inplace=True)
df3.rename(columns={'size':'Number'}, inplace=True)

In [69]:
df3.head()

    Bill   tip     sex smoker  day    time  Number
0  16.99  1.01  Female     No  Sun  Dinner       2
1  10.34  1.66    Male     No  Sun  Dinner       3
2  21.01  3.50    Male     No  Sun  Dinner       3
3  23.68  3.31    Male     No  Sun  Dinner       2
4  24.59  3.61  Female     No  Sun  Dinner       4

In [ ]:
#titanic[['Name','Age']] used to select a specific column from the dataset

df3[['Bill','tip','smoker']] #to select specific columns from the dataset

      Bill   tip smoker
0    16.99  1.01     No
1    10.34  1.66     No
2    21.01  3.50     No
3    23.68  3.31     No
4    24.59  3.61     No
..     ...   ...    ...
239  29.03  5.92     No
240  27.18  2.00    Yes
241  22.67  2.00    Yes
242  17.82  1.75     No
243  18.78  3.00     No

[244 rows x 3 columns]

In [ ]:
#in loc end is included but in iloc end is not included
df3.iloc[5:36:2,3:]#to select specific rows and columns from the dataset using iloc

NameError: name 'df3' is not defined

In [1]:
df3['tip'].astype('float 16')

NameError: name 'df3' is not defined

In [6]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [16]:
#change datatyppe of a column
titanic['survived'].astype('int32')
titanic['pclass'].astype('int32')

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: pclass, Length: 891, dtype: int32

In [17]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [19]:
titanic['survived'].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
(titanic['day']=="Sun")&(titanic['sex']=='Female').value_counts()) #to filter the dataset based on specific conditions

In [27]:
#In titanic count the person those age are below 25
((titanic['sex']=='male')&(titanic['age']<25)).value_counts()

False    730
True     161
Name: count, dtype: int64

In [ ]:
df=pd.DataFrame(data, index=labels)
df

In [ ]:
data = {'creatures': ['Eagles', 'Eagles', 'Ducks', 'Herons', 'Herons', 
'Eagles', 'Ducks', 'Eagles', 'Herons', 'Herons', 'Eagles'],  
'weight': [2.0, 5, 3.0, np.nan, 7, 2.5, 6, np.nan, 9, 3, 2.0],  
'frequency': [1, 3, 2, 5, 2, 3, 1, 3, 4, 2, 1],  
'status': ['no', 'no', 'yes', np.nan, 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 
'no'],  
'height': [1.2, 2.5, 1.8, 3.0, 2.2, 1.9, 2.6, 1.4, 2.8, 2.3, 1.1],  
'region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 
'West', 'North', 'East', 'South'],  
'danger_level': ['low', 'medium', 'high', 'low', 'high', 'medium', 
'high', 'low', 'medium', 'high', 'low']} 
labels = ['x', 'y', 'z', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p']